export const BOARD_ACTION_TYPES = {
    SET_HOVER_COLUMN: 'SET_HOVER_COLUMN',
    REFRESH_BOARDS: 'REFRESH_BOARDS',
    SET_LOADING: 'SET_LOADING',
    SET_CURRENT_BOARD: 'SET_CURRENT_BOARD',
    SET_CARD_BEING_PROCESSED: "SET_CARD_BEING_PROCESSED", 
    MOVE_CARD: "MOVE_CARD",
    SHOW_NEW_DUMMY_CARD: "SHOW_NEW_DUMMY_CARD",
    SET_COLUMN_TRANSFORMATION: "SET_COLUMN_TRANSFORMATION",
    DELETE_CARD:"DELETE_CARD"
}
