export const USER_ACTION_TYPES = {
    ATTEMPT_ACTION: 'ATTEMPT_ACTION',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    ATTEMPT_REGISTER: 'ATTEMPT_REGISTER',
    REGISTER_ERROR: 'REGISTER_ERROR',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    LOGOUT: 'LOGOUT'
};