name: Production CI/CD

on:
  release: 
    types: [published, created, edited]
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3

    - name: Debug
      run: |
        echo "Github.ref -> ${{ github.ref }}"
        
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
          context: .
          file: 'application.Dockerfile'
          push: true
          tags: 'atulvinod1911/thullo:latest'
          build-args: |
            unsplash_api_key=${{secrets.REACT_APP_UNSPLASH_API_KEY}}
            redis_host=${{secrets.REDIS_SETTINGS__HOST}}
            redis_port=${{secrets.REDIS_SETTINGS__PORT}}
            redis_password=${{secrets.REDIS_SETTINGS__PASSWORD}}
            db_host=${{secrets.DB__CONNECTIONS__MASTER__HOST}}
            db_user=${{secrets.DB__CONNECTIONS__MASTER__USERNAME}}
            db_password=${{secrets.DB__CONNECTIONS__MASTER__PASSWORD}}
            db_port=${{secrets.DB__CONNECTIONS__MASTER__PORT}}
            db_client=${{secrets.DATABASE_CLIENT}}
            db_database=${{secrets.DB__CONNECTIONS__MASTER__DATABASE}}
            
